### ISSUE TITLE
Contact us page

### ISSUE THREAD

**Issue by jimmythompson** [srobo/website#1]
There needs to be a contact us page available at `/{{baseurl}}/contact`. 

It would follow a similar format to https://www.studentrobotics.org/about/contactus.

Some of the content can likely be brought up to date as part of this, for example:

- the postal address is due to change, or maybe already has, so this needs to be confirmed (paging @rspanton),
- the email addresses should be changed to reflect the operations manual, and
- things like branch information could be moved to volunteer on-boarding.

**Comment by jimmythompson** [comment]
Apparently we have a new postal address, this needs updating before this can be closed.

**Comment by PeterJCLaw** [comment]
Interesting, let's get it onto srweb as well so that we're consistent.

**Comment by jimmythompson** [comment]
Rob says there is an address, but it's due to change shortly, so we'll wait for that.

**Comment by rspanton** [comment]
On Sun, 2016-05-29 at 10:28 -0700, Jimmy Thompson wrote:
> Rob says there is an address, but it's due to change shortly, so we'll wait
> for that.

Indeed.  It will hopefully emerge within a couple of weeks once the paperwork
for it has been processed.  (Currently SR's address is my house, but since I'm
moving house soon, this is changing to a much more permanent situation managed
by a mail-handling company.)

R
