### ISSUE TITLE
Nav bar on docs section leads to 404

### ISSUE THREAD

**Issue by shardros** [srobo/website#122]
When in the a section of the site where the URL is https://srobo.github.io/ the links in the navy bar point to the wrong places, giving a 404

**Comment by shardros** [comment]
I went to https://studentrobotics.org/docs/ then touched `programming` and I was redirected to srobo.github.io

**Comment by PeterJCLaw** [comment]
Aha, thanks.

This turns out to be an issue in how GitHub Pages handles redirects. I've reported the issue to GitHub, though also have a potential fix for our proxy config.

While that doesn't admittedly solve the issue if you do manage to reach `srobo.github.io`, it should make it much less likely that anyone actually does.

**Comment by shardros** [comment]
Ah okay, out of interest why do you have the GitHub pages site as well as the main site?

**Comment by PeterJCLaw** [comment]
We use GitHub Pages for hosting and proxy that into our own domain. Pages is great for hosting as it means that we (mostly) don't need to worry about the build/deploy steps ourselves.

**Comment by Adimote** [comment]
https://github.com/srobo/docs/pull/80 was merged and shipped, which fixes the links, so I'm gonna declare this fixed

**Comment by PeterJCLaw** [comment]
https://github.com/srobo/docs/pull/80 fixes some specific _causes_ of this, though neither fixes the actual issue, nor the general case cause. The actual links may not be worth fixing (since we don't really want people to get to the srobo.github.io pages anyway), though I think the general case of the cause is.

I've put up #123 which improves our handling of GitHub's urls via a tweak to our proxy config, applied across all the github.io domains we use.

This was the bug which I'd reported to GitHub. I'd originally been concerned that it might be considered a security issue (hence the obliqueness about it in my earlier comments), but they've confirmed that they don't consider it sensitive.

Essentially the issue is that when redirecting from from `/docs/programming` to `/docs/programming/` a redirect is issued to `http://srobo.github.io/docs/programming/` (note the `http://` protocol). As that (insecure) url is different to the url which our proxy is expecting, the proxy misses it.
