### ISSUE TITLE
Links on back of boards are broken

### ISSUE THREAD

**Issue by trickeydan** [srobo/website#151]
e.g
- srobo.org/sbv4
- srobo.org/mcv4
- srobo.org/bv4

**Comment by PeterJCLaw** [comment]
I'm not sure these have ever worked.
I think @richardbarlow had originally planned for those to link to the schematics of the boards.
It might make sense for them to link to the docs in the meanwhile though?

Note that currently those urls are doubly broken due to `srobo.org` not working (https://github.com/srobo/infrastructure/issues/4).

**Comment by sedders123** [comment]
Now that srobo.org is back, these should be fixable by amending the nginx config in [srobo/ansible](https://github.com/srobo/ansible) (Once https://github.com/srobo/ansible/pull/1 has been merged)

**Comment by sedders123** [comment]
Hi @srobo/kit-team What are the desired destinations of these short links? Happy to put together a PR to fix them but not sure if we should be linking to schematics, firmware, the docs or something else?

**Comment by WillB97** [comment]
- https://studentrobotics.org/docs/kit/servo_board 
- https://studentrobotics.org/docs/kit/motor_board
- https://studentrobotics.org/docs/kit/power_board

These would work fine, there is also one on the kch but the page doesn't exist yet.
