### ISSUE TITLE
Obtain analytics

### ISSUE THREAD

**Issue by antoinepetty** [srobo/website#288]
We have some analytics tools in place already but not sure where they go or if they need upgrading

**Comment by PeterJCLaw** [comment]
There are two that I know of:
- Google Analytics: we have an account, not sure who manages it/where it is, nor even if it's part of our G-Suite or not
- Piwik: we used to run our own instance of [Piwik](https://piwik.com/) on `saffron`, however that's not been running for a very long time

Suggest picking a single analytics tool and then standardising around that.

**Comment by antoinepetty** [comment]
looks like Piwik has a successor https://matomo.org/ - might be worth looking into

**Comment by sedders123** [comment]
[Plausible](https://plausible.io/) is another contender, I know @RealOrangeOne has experience using it

**Comment by RealOrangeOne** [comment]
Piwik rebranded into Matomo a couple years back. 

For something like this hosting ourselves is probably something we want to avoid, just because it's unlikely to be worth the effort.

Assuming we can get Google Analytics setup in a way which doesn't require a banner, that's definitely easiest, although there's a high chance GA is blocked by our target audience https://plausible.io/blog/google-analytics-adblockers-missing-data.

Plausible is great (disclaimer, I have contributed [a lot](https://plausible.io/docs/authors#contributors) to them), they do good things as a company, and have a reasonable price. If we're interested, I could try reaching out?

**Comment by antoinepetty** [comment]
@RealOrangeOne looks like Plausible would be one of the better options - we'd love you to reach out and find out what's possible please

**Comment by RealOrangeOne** [comment]
I have reached out.
