### ISSUE TITLE
/password no longer exists

### ISSUE THREAD

**Issue by thomasleese** [srobo/website#47]
https://www.studentrobotics.org/password used to point to a page allowing users to change their passwords, but it no longer appears to work.

This is a problem as the email sent out detailing how teams can change their passwords included this link.

**Comment by PeterJCLaw** [comment]
Hi,

The `/password` page has not worked for several years, though I think it
has been redirecting to `/userman`. Either way we should not be advertising
it any more. The fix is therefore:

- change all links to use `/userman` (which is documented and canonical); I
had thought this had been done _years_ ago
- possibly redirect from `/password` to `/userman` if links have already
gone out

Please do not proxy `/password` onto `/userman` as the duplication will
confuse people ("which one is right", "what happens if I change my password
in the wrong one"; while such questions are meaningless, even having a
system which causes them to be asked is broken).

Thanks,
Peter

**Comment by PeterJCLaw** [comment]
Urgh, so it turns out that the email in question is the template in the command-line userman tool (https://www.studentrobotics.org/cgit/userman.git/tree/msg/english/teacher_welcome), so that's my fault (sorry).

The point about not double-proxying `/userman` stands though; I'll submit a PR for that shortly.

**Comment by PeterJCLaw** [comment]
Duplicate proxy fixed in #51.
